FROM debian:bullseye

RUN apt update && apt install -y vim mariadb-server php-mysql

RUN service mariadb start
CMD sleep 9000000

# RUN mysql_secure_installation <<EOF

# y
# 1598753246
# 1598753246
# y
# y
# y
# y
# EOF