version: '3'

services:
  nginx:
    image: inception:nginx
    container_name: nginx
    build: ./requirements/nginx/
    # depends_on:
    #   - portfolio
    ports:
      - 443:443
    networks:
      - net
    volumes:
      - wordpress_volume:/var/www/html
    restart: always
    
  wordpress:
    image: inception:wordpress
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - net
    env_file:
      - .env
    restart: always
    
  mariadb:
    image: inception:mariadb
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - net
    env_file:
      - .env
    restart: always

  # portfolio:
  #   image: inception:portfolio
  #   container_name: portfolio
  #   build: ./requirements/bonus/portfolio
  #   volumes:
  #     - portfolio_volume:/var/www/html
  #   networks:
  #     - net
  #   env_file:
  #     - .env
  #   restart: always

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/abouabra/data/mariadb
      o: bind
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/abouabra/data/wordpress
      o: bind
  # portfolio_volume:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /home/abouabra/data/portfolio
  #     o: bind



networks:
  net:
    driver: bridge