version: '3'

services:
  nginx:
    image: inception:nginx
    container_name: nginx
    build: ./requirements/nginx/
    depends_on:
      - portfolio
    ports:
      - 443:443
    networks:
      - net
    volumes:
      - wordpress_volume:/var/www/html
    restart: always
    
  wordpress:
    image: inception:wordpress
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - net
    env_file:
      - .env
    restart: always
    
  mariadb:
    image: inception:mariadb
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - net
    env_file:
      - .env
    restart: always

  portfolio:
    image: inception:portfolio
    container_name: portfolio
    build: ./requirements/bonus/portfolio
    networks:
      - net
    env_file:
      - .env
    restart: always

  netdata:
    image: inception:netdata
    container_name: netdata
    build: ./requirements/bonus/netdata
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
    ports:
      - 2003:19999
    restart: always

  adminer:
    image: inception:adminer
    container_name: adminer
    build: ./requirements/bonus/adminer
    depends_on:
      - mariadb
    networks:
      - net
    env_file:
      - .env
    restart: always

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/abouabra/data/mariadb
      o: bind
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/abouabra/data/wordpress
      o: bind


networks:
  net:
    driver: bridge